# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Caleb Evans
tagline: Coder for Christ
email: caleb@calebevans.me
gravatar_size: 60
description: > # this means to ignore newlines until "baseurl:"
  This is the personal website of Caleb Evans, rewritten entirely in Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://calebevans.me" # the base hostname & protocol for your site
twitter_username: caleb531
github_username:  caleb531

# Build settings
markdown: kramdown

# Collections used for new content types
collections:
  # Personal projects
  projects:
    output: false
