# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Caleb Evans
tagline: Coder for Christ
email: caleb@calebevans.me
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Caleb, a college student who lives for Christ by coding awesome apps and tools. Come see what I've made!
baseurl: '' # the subpath of your site, e.g. /blog
url: http://calebevans.me # the base hostname & protocol for your site

# Twitter SEO settings
twitter:
  username: caleb531

# Google tokens
google_site_verification: hgENNCrZvitO_dtrCT_F6VdV1YspqEDh-nBMoq0dL5g
google_analytics: UA-32415253-1

# Serve settings
host: 0.0.0.0 # Enables local site to be accessed from other devices on network

# Build settings
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: :compressed
include:
  - _pages
  - .htaccess
exclude:
  - README.md
  - LICENSE.txt
  - deploy.sh

# Collections used for new content types
collections:
  # Personal projects
  projects:
    output: false
  # Portfolio websites
  websites:
    output: false
  # Contact links (displayed in footer and on Contact page)
  contact_links:
    output: false
